# Data sources

The dataset for our project is `speed dating` dataset provided by Anna Montoya. It is publicly available on [Data.com](https://data.world/annavmontoya/speed-dating-experiment) as an excel file. 

The data contains information about match and questionnaire from a speed dating experiment in 2002-2004 that was run by professors Ray Fisman and Sheena Iyengar from Columbia Business School. The primamry purpose of the collection was for their paper [Gender Differences in Mate Selection: Evidence From a Speed Dating Experiment](https://faculty.chicagobooth.edu/emir.kamenica/documents/genderDifferences.pdf). 

## Experimental Design

The experiment is design based on *Speed Dating* which is an event where participants have a four-minute conversation and decide if they want to meet each other again. They will get the other's contact information only if both parties "accept".

Subjects in the experiments were students in graduate and professional school at Columbia University during the time of the experiment. They learned about the event through mass e-mail and fliers on distributed on campus. They had to sign up for the event by providing the experimentors with their names and email addresses and completing a pre-event survey ononline website. 

There were 20 sessions of the experiment, all of which had the same setting. All participants were randomly assigned to one of the sessions. On the session day, participants who are unawared of the total number of participants on that day had to fill in a scorecard that contains 

* Spaces to write the ID number of each person they met
* Yes/No whether a subject wants to meet the person again
* Six attributes on which a subject was to rate the person they met. The attributes are:
    * Attractive
    * Sincere
    * Intelligent
    * Fun
    * Ambitious
    * Shared Interests
    
There were roughly the same number of female and male participants in each sessions. Subjects only had conversation with those of different genders. Female subjects would meet all male subjects in the session. The scorecard was to be filled after each four-minute conversation.

The day after the *Speed Dating* event, particiapants were asked to complete the follow-up online questionaire in order to obtain their matches. For more detail on the experiment procedure, please check out the [study](https://faculty.chicagobooth.edu/emir.kamenica/documents/genderDifferences.pdf).


## Data Description

For more information about the data, see the [metadata](https://github.com/bojum/speeddating/blob/master/data/Speed%20Dating%20Data%20Key.doc?raw=true) from the dataset provider. 


